from flask import Blueprint, render_template

from utils.analytics.revenue import (

    get_revenue_kpis,

    get_monthly_adr,

    get_hotel_revenue,

    get_market_segment_adr,

    get_weekend_weekday_adr,

    get_customer_type_adr

)

# Create a Blueprint for the Revenue Analytics module.
# This blueprint handles all revenue-related routes.
revenue_bp = Blueprint(

    "revenue",

    __name__

)


# Route for the Revenue Analytics Dashboard.
# Displays revenue KPIs and visualizations related
# to ADR, hotel revenue, market segments, and customer types.
@revenue_bp.route("/revenue")
def revenue():

    # Render the revenue dashboard template and pass
    # all revenue-related analytical data.
    return render_template(

        "revenue.html",

        # Revenue KPI cards.
        kpis=get_revenue_kpis(),

        # Monthly Average Daily Rate (ADR) trend.
        monthly=get_monthly_adr(),

        # Revenue generated by each hotel type.
        hotels=get_hotel_revenue(),

        # Average ADR across different market segments.
        segments=get_market_segment_adr(),

        # Revenue comparison between weekday and weekend stays.
        stay=get_weekend_weekday_adr(),

        # Average ADR by customer type.
        customers=get_customer_type_adr()

    )