import os

from flask import (
    Flask,
    render_template,
    request,
    redirect,
    flash
)

from werkzeug.utils import secure_filename
from utils.preprocess import preprocess_image
from utils.predict import predict_image

from utils.gradcam import (
    generate_gradcam,
    save_gradcam,
    get_last_conv_layer
)



from utils.predict import model

app = Flask(__name__)

app.secret_key = "my_secret_key"

UPLOAD_FOLDER = "static/uploads"

ALLOWED_EXTENSIONS = {
    "jpg",
    "jpeg",
    "png"
}

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

app.config["UPLOAD_FOLDER"] = os.path.join(BASE_DIR, "static", "uploads")
app.config["GRADCAM_FOLDER"] = os.path.join(BASE_DIR, "static", "gradcam")

os.makedirs(app.config["UPLOAD_FOLDER"], exist_ok=True)
os.makedirs(app.config["GRADCAM_FOLDER"], exist_ok=True)

def allowed_file(filename):

    return (
        "." in filename
        and
        filename.rsplit(".", 1)[1].lower()
        in ALLOWED_EXTENSIONS
    )


@app.route("/")
def home():
    return render_template("home.html")


@app.route("/upload", methods=["GET", "POST"])
def upload():

    if request.method == "POST":

        image = request.files.get("image")

        if image is None:
            flash("No file was uploaded.")
            return redirect(request.url)

        if image.filename == "":
            flash("Please select an image.")
            return redirect(request.url)

        if not allowed_file(image.filename):
            flash("Only JPG, JPEG and PNG files are allowed.")
            return redirect(request.url)


        filename = secure_filename(image.filename)

        save_path = os.path.join(
            app.config["UPLOAD_FOLDER"],
            filename
        )

        image.save(save_path)

        processed_image = preprocess_image(
            save_path
        )

        predicted_class, confidence, probability_data = predict_image(
            processed_image
        )

        last_conv_layer = get_last_conv_layer(
            model
        )

        heatmap = generate_gradcam(
            model=model,
            image=processed_image,
            last_conv_layer_name=last_conv_layer
        )

        gradcam_filename = f"gradcam_{filename}"

        gradcam_save_path = os.path.join(
            BASE_DIR,
            app.config["GRADCAM_FOLDER"],
            gradcam_filename
        )

        save_gradcam(
            save_path,
            heatmap,
            gradcam_save_path
        )


        image_path = f"uploads/{filename}"

        gradcam_path = f"gradcam/{gradcam_filename}"
        

        print("=================================================================")

        print(image_path)
        print(gradcam_path)

        print("=================================================================")

        disease_info = {

            "description":

            "This prediction is generated by a trained Deep Learning model. "
            "It should not replace professional medical advice.",

            "recommendation":

            "Please consult a certified dermatologist for clinical confirmation."

        }

        return render_template(
            "result.html",
            image_path=image_path,
            disease_info=disease_info,
            gradcam_path=gradcam_path,
            predicted_class=predicted_class,
            confidence=confidence,
            probability_data=probability_data
        )

    return render_template("upload.html")


@app.route("/dashboard")
def dashboard():

    return render_template(
        "dashboard.html",

        total_images=10015,

        total_classes=7,

        best_model="BasicCNN",

        train_count=7010,

        validation_count=1502,

        test_count=1503
    )


@app.route("/analytics")
def analytics():

    metrics = {

        "accuracy":58.09,

        "precision":74.50,

        "recall":58.32,

        "f1":62.89

    } 

    return render_template(

        "analytics.html",

        metrics=metrics

    )

@app.route("/reports")
def reports():

    diagnosis_available = True

    comparison_available = True

    return render_template(
        "reports.html",
        diagnosis_available=diagnosis_available,
        comparison_available=comparison_available
    )

if __name__ == "__main__":
    app.run(debug=True)